#!/bin/bash

# Claude Flow Dagger Module - Docker Test Script
# 
# This script tests the module using Docker directly without Dagger
# Usage: ./test/docker-test.sh

set -e

echo "🚀 Claude Flow Docker Test Script"
echo "=================================="
echo ""

# Check required environment variables
if [ -z "$GITHUB_TOKEN" ]; then
    echo "❌ Error: GITHUB_TOKEN environment variable is required"
    echo "Please set: export GITHUB_TOKEN=your_github_token"
    exit 1
fi

if [ -z "$ANTHROPIC_AUTH_TOKEN" ] && [ -z "$CLAUDE_API_KEY" ]; then
    echo "❌ Error: ANTHROPIC_AUTH_TOKEN or CLAUDE_API_KEY environment variable is required"
    echo "Please set: export ANTHROPIC_AUTH_TOKEN=your_anthropic_token"
    exit 1
fi

# Set variables
REPO_URL="https://github.com/badal-io/claude-test-repo.git"
BRANCH_NAME="claude-flow-test-$(date +%s)"
ANTHROPIC_TOKEN="${ANTHROPIC_AUTH_TOKEN:-$CLAUDE_API_KEY}"
ANTHROPIC_BASE_URL="${ANTHROPIC_BASE_URL:-https://api.anthropic.com}"

echo "📋 Configuration:"
echo "  Repository: badal-io/claude-test-repo"
echo "  Branch: $BRANCH_NAME"
echo "  GitHub Token: ${GITHUB_TOKEN:0:8}..."
echo "  Anthropic Token: ${ANTHROPIC_TOKEN:0:8}..."
echo ""

# Create a temporary directory for the test
TEST_DIR=$(mktemp -d)
echo "📁 Working directory: $TEST_DIR"
echo ""

# Step 1: Clone the repository
echo "1️⃣ Cloning repository..."
cd "$TEST_DIR"
git clone "https://${GITHUB_TOKEN}@github.com/badal-io/claude-test-repo.git" workspace
cd workspace

# Configure git
git config user.email "claude-flow-bot@example.com"
git config user.name "Claude Flow Bot"

# Step 2: Create a new branch
echo "2️⃣ Creating branch $BRANCH_NAME..."
git checkout -b "$BRANCH_NAME"

# Step 3: Run claude-flow with hive-mind using Docker
echo "3️⃣ Running claude-flow hive-mind..."
echo ""

# Initialize hive-mind
docker run --rm \
    -v "$(pwd):/workspace" \
    -w /workspace \
    -e CLAUDE_FLOW_NON_INTERACTIVE=true \
    -e ANTHROPIC_AUTH_TOKEN="$ANTHROPIC_TOKEN" \
    -e ANTHROPIC_BASE_URL="$ANTHROPIC_BASE_URL" \
    -e DEBUG=true \
    ghcr.io/liamhelmer/claude-flow-dagger:latest \
    claude-flow hive-mind init

# Spawn hive-mind task
CLAUDE_OUTPUT=$(docker run --rm \
    -v "$(pwd):/workspace" \
    -w /workspace \
    -e CLAUDE_FLOW_NON_INTERACTIVE=true \
    -e ANTHROPIC_AUTH_TOKEN="$ANTHROPIC_TOKEN" \
    -e ANTHROPIC_BASE_URL="$ANTHROPIC_BASE_URL" \
    -e DEBUG=true \
    ghcr.io/liamhelmer/claude-flow-dagger:latest \
    claude-flow hive-mind spawn "build a nodejs hello world app" --claude --non-interactive 2>&1)

echo "$CLAUDE_OUTPUT" | head -20
echo "..."
echo ""

# Step 4: Check for changes and commit
echo "4️⃣ Checking for changes..."
if [ -n "$(git status --porcelain)" ]; then
    echo "✅ Changes detected, committing..."
    git add -A
    git commit -m "feat: build hello world app with Claude Flow

Generated using Claude Flow Dagger module with hive-mind.
Branch: $BRANCH_NAME
Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    
    # Push changes
    echo "📤 Pushing to remote..."
    git push "https://${GITHUB_TOKEN}@github.com/badal-io/claude-test-repo.git" "$BRANCH_NAME"
else
    echo "⚠️ No changes detected"
fi

# Step 5: Create pull request using GitHub CLI in Docker
echo "5️⃣ Creating pull request..."

PR_BODY="## 🤖 Claude Flow Generated Hello World App

This pull request was automatically generated by Claude Flow Dagger module using hive-mind.

### What was done:
- Initialized hive-mind collective intelligence
- Spawned task to build a Node.js hello world application
- Generated all necessary files and configuration

### Branch: $BRANCH_NAME
### Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

---
*This PR was created automatically by Claude Flow Test Workflow*"

# Create PR using gh CLI
docker run --rm \
    -v "$(pwd):/workspace" \
    -w /workspace \
    -e GITHUB_TOKEN="$GITHUB_TOKEN" \
    ghcr.io/liamhelmer/claude-flow-dagger:latest \
    gh pr create \
        --base main \
        --head "$BRANCH_NAME" \
        --title "🤖 Claude Flow: Hello World App" \
        --body "$PR_BODY" \
        --repo badal-io/claude-test-repo

# Step 6: Test the generated app
echo "6️⃣ Testing the generated app..."
echo ""

# Look for JavaScript files
if [ -f "index.js" ] || [ -f "app.js" ] || [ -f "server.js" ] || [ -f "hello.js" ]; then
    echo "✅ Found JavaScript files"
    
    # Find the main file
    MAIN_FILE=""
    for file in index.js app.js server.js main.js hello.js; do
        if [ -f "$file" ]; then
            MAIN_FILE="$file"
            break
        fi
    done
    
    if [ -n "$MAIN_FILE" ]; then
        echo "📄 Testing $MAIN_FILE..."
        
        # Install dependencies if package.json exists
        if [ -f "package.json" ]; then
            echo "📦 Installing dependencies..."
            docker run --rm \
                -v "$(pwd):/workspace" \
                -w /workspace \
                ghcr.io/liamhelmer/claude-flow-dagger:latest \
                npm install
        fi
        
        # Run the app
        OUTPUT=$(docker run --rm \
            -v "$(pwd):/workspace" \
            -w /workspace \
            ghcr.io/liamhelmer/claude-flow-dagger:latest \
            node "$MAIN_FILE" 2>&1)
        
        echo "Output: $OUTPUT"
        
        # Check for "hello world"
        if echo "$OUTPUT" | grep -qi "hello" && echo "$OUTPUT" | grep -qi "world"; then
            echo "✅ App successfully outputs 'hello world'!"
        else
            echo "⚠️ App doesn't output 'hello world', but file was created"
            # Check file content
            if grep -qi "hello" "$MAIN_FILE" && grep -qi "world" "$MAIN_FILE"; then
                echo "✅ File contains 'hello world' text"
            fi
        fi
    fi
else
    echo "⚠️ No JavaScript files found"
    # List what was created
    echo "Files created:"
    ls -la
fi

# Cleanup
echo ""
echo "🧹 Cleaning up..."
cd /
rm -rf "$TEST_DIR"

echo ""
echo "✅ Test completed successfully!"
echo "Check the pull request at: https://github.com/badal-io/claude-test-repo/pulls"